language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t pablitod79/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true pablitod79/docker-react npm run test
